// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: api/task/service/v1/task.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on GetIntegratingReq with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GetIntegratingReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetIntegratingReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetIntegratingReqMultiError, or nil if none found.
func (m *GetIntegratingReq) ValidateAll() error {
	return m.validate(true)
}

func (m *GetIntegratingReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for UserId

	if len(errors) > 0 {
		return GetIntegratingReqMultiError(errors)
	}

	return nil
}

// GetIntegratingReqMultiError is an error wrapping multiple validation errors
// returned by GetIntegratingReq.ValidateAll() if the designated constraints
// aren't met.
type GetIntegratingReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetIntegratingReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetIntegratingReqMultiError) AllErrors() []error { return m }

// GetIntegratingReqValidationError is the validation error returned by
// GetIntegratingReq.Validate if the designated constraints aren't met.
type GetIntegratingReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetIntegratingReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetIntegratingReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetIntegratingReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetIntegratingReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetIntegratingReqValidationError) ErrorName() string {
	return "GetIntegratingReqValidationError"
}

// Error satisfies the builtin error interface
func (e GetIntegratingReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetIntegratingReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetIntegratingReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetIntegratingReqValidationError{}

// Validate checks the field values on GetIntegratingReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetIntegratingReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetIntegratingReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetIntegratingReplyMultiError, or nil if none found.
func (m *GetIntegratingReply) ValidateAll() error {
	return m.validate(true)
}

func (m *GetIntegratingReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Grade

	if len(errors) > 0 {
		return GetIntegratingReplyMultiError(errors)
	}

	return nil
}

// GetIntegratingReplyMultiError is an error wrapping multiple validation
// errors returned by GetIntegratingReply.ValidateAll() if the designated
// constraints aren't met.
type GetIntegratingReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetIntegratingReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetIntegratingReplyMultiError) AllErrors() []error { return m }

// GetIntegratingReplyValidationError is the validation error returned by
// GetIntegratingReply.Validate if the designated constraints aren't met.
type GetIntegratingReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetIntegratingReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetIntegratingReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetIntegratingReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetIntegratingReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetIntegratingReplyValidationError) ErrorName() string {
	return "GetIntegratingReplyValidationError"
}

// Error satisfies the builtin error interface
func (e GetIntegratingReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetIntegratingReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetIntegratingReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetIntegratingReplyValidationError{}

// Validate checks the field values on IntegratingCountReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *IntegratingCountReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on IntegratingCountReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// IntegratingCountReqMultiError, or nil if none found.
func (m *IntegratingCountReq) ValidateAll() error {
	return m.validate(true)
}

func (m *IntegratingCountReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return IntegratingCountReqMultiError(errors)
	}

	return nil
}

// IntegratingCountReqMultiError is an error wrapping multiple validation
// errors returned by IntegratingCountReq.ValidateAll() if the designated
// constraints aren't met.
type IntegratingCountReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m IntegratingCountReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m IntegratingCountReqMultiError) AllErrors() []error { return m }

// IntegratingCountReqValidationError is the validation error returned by
// IntegratingCountReq.Validate if the designated constraints aren't met.
type IntegratingCountReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e IntegratingCountReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e IntegratingCountReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e IntegratingCountReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e IntegratingCountReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e IntegratingCountReqValidationError) ErrorName() string {
	return "IntegratingCountReqValidationError"
}

// Error satisfies the builtin error interface
func (e IntegratingCountReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sIntegratingCountReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = IntegratingCountReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = IntegratingCountReqValidationError{}

// Validate checks the field values on IntegratingCountReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *IntegratingCountReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on IntegratingCountReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// IntegratingCountReplyMultiError, or nil if none found.
func (m *IntegratingCountReply) ValidateAll() error {
	return m.validate(true)
}

func (m *IntegratingCountReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return IntegratingCountReplyMultiError(errors)
	}

	return nil
}

// IntegratingCountReplyMultiError is an error wrapping multiple validation
// errors returned by IntegratingCountReply.ValidateAll() if the designated
// constraints aren't met.
type IntegratingCountReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m IntegratingCountReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m IntegratingCountReplyMultiError) AllErrors() []error { return m }

// IntegratingCountReplyValidationError is the validation error returned by
// IntegratingCountReply.Validate if the designated constraints aren't met.
type IntegratingCountReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e IntegratingCountReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e IntegratingCountReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e IntegratingCountReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e IntegratingCountReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e IntegratingCountReplyValidationError) ErrorName() string {
	return "IntegratingCountReplyValidationError"
}

// Error satisfies the builtin error interface
func (e IntegratingCountReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sIntegratingCountReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = IntegratingCountReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = IntegratingCountReplyValidationError{}
