// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: api/job/service/v1/job.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on IntegratingJobReq with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *IntegratingJobReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on IntegratingJobReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// IntegratingJobReqMultiError, or nil if none found.
func (m *IntegratingJobReq) ValidateAll() error {
	return m.validate(true)
}

func (m *IntegratingJobReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return IntegratingJobReqMultiError(errors)
	}

	return nil
}

// IntegratingJobReqMultiError is an error wrapping multiple validation errors
// returned by IntegratingJobReq.ValidateAll() if the designated constraints
// aren't met.
type IntegratingJobReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m IntegratingJobReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m IntegratingJobReqMultiError) AllErrors() []error { return m }

// IntegratingJobReqValidationError is the validation error returned by
// IntegratingJobReq.Validate if the designated constraints aren't met.
type IntegratingJobReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e IntegratingJobReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e IntegratingJobReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e IntegratingJobReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e IntegratingJobReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e IntegratingJobReqValidationError) ErrorName() string {
	return "IntegratingJobReqValidationError"
}

// Error satisfies the builtin error interface
func (e IntegratingJobReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sIntegratingJobReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = IntegratingJobReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = IntegratingJobReqValidationError{}

// Validate checks the field values on IntegratingJobReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *IntegratingJobReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on IntegratingJobReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// IntegratingJobReplyMultiError, or nil if none found.
func (m *IntegratingJobReply) ValidateAll() error {
	return m.validate(true)
}

func (m *IntegratingJobReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return IntegratingJobReplyMultiError(errors)
	}

	return nil
}

// IntegratingJobReplyMultiError is an error wrapping multiple validation
// errors returned by IntegratingJobReply.ValidateAll() if the designated
// constraints aren't met.
type IntegratingJobReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m IntegratingJobReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m IntegratingJobReplyMultiError) AllErrors() []error { return m }

// IntegratingJobReplyValidationError is the validation error returned by
// IntegratingJobReply.Validate if the designated constraints aren't met.
type IntegratingJobReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e IntegratingJobReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e IntegratingJobReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e IntegratingJobReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e IntegratingJobReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e IntegratingJobReplyValidationError) ErrorName() string {
	return "IntegratingJobReplyValidationError"
}

// Error satisfies the builtin error interface
func (e IntegratingJobReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sIntegratingJobReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = IntegratingJobReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = IntegratingJobReplyValidationError{}
